// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bj_core_cpp
Rcpp::List bj_core_cpp(const NumericMatrix& X, const NumericVector& y, const NumericVector& weights, const IntegerVector& block_id, const bool keep_delete);
RcppExport SEXP _blockjack_bj_core_cpp(SEXP XSEXP, SEXP ySEXP, SEXP weightsSEXP, SEXP block_idSEXP, SEXP keep_deleteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type block_id(block_idSEXP);
    Rcpp::traits::input_parameter< const bool >::type keep_delete(keep_deleteSEXP);
    rcpp_result_gen = Rcpp::wrap(bj_core_cpp(X, y, weights, block_id, keep_delete));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_blockjack_bj_core_cpp", (DL_FUNC) &_blockjack_bj_core_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_blockjack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
