# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bj_core_cpp <- function(X, y, weights, block_id, keep_delete) {
    .Call('_blockjack_bj_core_cpp', PACKAGE = 'blockjack', X, y, weights, block_id, keep_delete)
}

